### ISSUE TITLE
Authentification with NextAuth

### ISSUE THREAD

**Issue by Lugdu84** [Lugdu84/dev-up#3]
Implémentation du système d'authentification (NextAuth)

- [x] installation de NextAuth 
- [x] création des apis
- [x] Connexion avec GitHub
- [x] Connexion avec Google

**Comment by GuillaumeCeccoli** [comment]
On peut également ajouter des commentaires ;)

**Comment by 7h0ma5Thomas** [comment]
@GuillaumeCeccoli Et identifier des collaborateurs
